<?php session_start(); ?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Dezenas de robôs &#039;protestam&#039; contra uso descontrolado da IA na Polônia Dezenas de robôs &#039;protestam&#039; contra uso descontrolado da IA na Polônia | ByteNews</title><link rel="stylesheet" href="../../assets/CSS/style.css"><link rel="icon" href="../../assets/icons/icone.png"></head>
<body class="dark" data-news-id="18">
<?php $headerBasePath = '../../../'; require __DIR__ . '/../../php/header.php'; ?>
<main><section class="news-article"><div class="news-title"><span class="news-card_category tecnologia">Robótica</span><h1>Dezenas de robôs &#039;protestam&#039; contra uso descontrolado da IA na Polônia Dezenas de robôs &#039;protestam&#039; contra uso descontrolado da IA na Polônia</h1><p>Agitando bandeiras, entoando slogans e marchando em círculo, cerca de 30 robôs foram às ruas de Varsóvia nesta segunda-feira (7) para exigir que a Polônia regulamente a inteligência artificial (IA).</p><p>Por Lucas Reis Souza</p></div><figure class="news-image"><img src="../../assets/images/dezenas-de-rob-os-protestam-contra-uso-descontrolado-da-ia-na-pol-onia-dezenas-de-rob-os-protestam-contra-uso-descontrolado-da-ia-na-pol-onia-972bad3f.png" alt="Dezenas de robôs &#039;protestam&#039; contra uso descontrolado da IA na Polônia Dezenas de robôs &#039;protestam&#039; contra uso descontrolado da IA na Polônia"></figure><article class="news-content"><p>A marcha foi organizada pelo &quot;Democratism&quot;, iniciativa que, segundo seu site, busca promover o debate sobre &quot;como a IA e a robotização afetam o mercado de trabalho&quot;.</p><p>&quot;Os robôs aqui presentes devem mostrar que essa tecnologia já é uma realidade&quot;, disse à AFP o Agibot A3, robô humanoide equipado com IA.<br />
<br />
Slogans como &quot;Defendam os empregos&quot;, &quot;Chegou a hora das regras&quot; e &quot;Não esperem, regulamentem&quot; podiam ser ouvidos nos alto-falantes dos robôs.</p><p>&quot;Se não reagirmos agora, poderemos ter um problema em breve&quot;, acrescentou, salientando a necessidade de &quot;regras e regulamentos que sirvam de escudo protetor para os trabalhadores&quot;.<br />
<br />
O protesto ocorreu em frente ao Ministério de Assuntos Digitais, e seu titular, Krzysztof Gawkowski, aproximou-se e conversou com Kulis.<br />
<br />
&quot;Modelos de IA sem controle, implementados em humanoides que continuarão evoluindo com o avanço da robotização, representam um problema grave&quot;, disse o ministro.</p><h2>dfçanberbgodmskdmjnjrbfjdkso</h2><p>&quot;Se não reagirmos agora, poderemos ter um problema em breve&quot;, acrescentou, salientando a necessidade de &quot;regras e regulamentos que sirvam de escudo protetor para os trabalhadores&quot;.<br />
<br />
O protesto ocorreu em frente ao Ministério de Assuntos Digitais, e seu titular, Krzysztof Gawkowski, aproximou-se e conversou com Kulis.<br />
<br />
&quot;Modelos de IA sem controle, implementados em humanoides que continuarão evoluindo com o avanço da robotização, representam um problema grave&quot;, disse o ministro.</p></article><section class="news-comments" aria-labelledby="commentsTitle"><h2 id="commentsTitle" class="news-comments-title">Vejam o que os usuários estão comentando</h2><div id="commentsList" class="comments-list" aria-live="polite"></div><form id="commentForm" class="comment-form"><label for="commentText">Seu comentário</label><textarea id="commentText" name="comment" placeholder="Escreva seu comentário..."></textarea><p id="commentError" class="comment-error" role="alert"></p><p class="comment-login-message">Seu nome será exibido junto ao comentário.</p><button id="commentButton" class="comment-button" type="submit">Comentar</button></form></section></section></main>
</body></html>