<?php
require_once __DIR__ . '/../../php/conexao.php';
$slug = preg_replace('/[^a-z0-9-]/', '', strtolower($_GET['slug'] ?? ''));
$idNoticia = (int) ($_GET['id_noticia'] ?? 0);
if ($slug !== '') { $stmt = $conexao->prepare('SELECT id_noticia, titulo, subtitulo, conteudo, categoria, autor, data_publicacao, imagem FROM noticias WHERE slug = ? LIMIT 1'); $stmt->bind_param('s', $slug); }
else { $stmt = $conexao->prepare('SELECT id_noticia, titulo, subtitulo, conteudo, categoria, autor, data_publicacao, imagem FROM noticias WHERE id_noticia = ? LIMIT 1'); $stmt->bind_param('i', $idNoticia); }
$stmt->execute(); $noticia = $stmt->get_result()->fetch_assoc();
if (!$noticia) { http_response_code(404); exit('Notícia não encontrada.'); }
$blocos = json_decode($noticia['conteudo'], true);
if (!is_array($blocos)) $blocos = array_map(static fn (string $texto) => ['tipo' => 'paragrafo', 'conteudo' => $texto], array_filter(preg_split('/\R{2,}/', $noticia['conteudo'])));
?>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= htmlspecialchars($noticia['titulo']) ?> | ByteNews</title><link rel="stylesheet" href="../../assets/CSS/style.css"><link rel="icon" href="../../assets/icons/icone.png"></head>
<body class="dark" data-news-id="<?= (int) $noticia['id_noticia'] ?>">
<?php $headerBasePath = '../../../'; require __DIR__ . '/../../php/header.php'; ?>
<main><section class="news-article"><div class="news-title"><span class="news-card_category tecnologia"><?= htmlspecialchars($noticia['categoria']) ?></span><h1><?= htmlspecialchars($noticia['titulo']) ?></h1><?php if ($noticia['subtitulo'] !== ''): ?><p><?= htmlspecialchars($noticia['subtitulo']) ?></p><?php endif; ?><p>Por <?= htmlspecialchars($noticia['autor']) ?> | <?= date('d/m/Y H:i', strtotime($noticia['data_publicacao'])) ?></p></div><figure class="news-image"><img src="../../assets/images/<?= htmlspecialchars(basename($noticia['imagem'])) ?>" alt="<?= htmlspecialchars($noticia['titulo']) ?>"></figure><article class="news-content"><?php foreach ($blocos as $bloco): $tipo = $bloco['tipo'] ?? 'paragrafo'; $texto = htmlspecialchars((string) ($bloco['conteudo'] ?? '')); if ($tipo === 'titulo'): ?><h2><?= $texto ?></h2><?php elseif ($tipo === 'recuado'): ?><p class="news-paragraph-indented"><?= nl2br($texto) ?></p><?php else: ?><p><?= nl2br($texto) ?></p><?php endif; endforeach; ?></article><section class="news-comments" aria-labelledby="commentsTitle"><h2 id="commentsTitle" class="news-comments-title">Comentários</h2><div id="commentsList" class="comments-list" aria-live="polite"></div><form id="commentForm" class="comment-form"><label for="commentText">Seu comentário</label><textarea id="commentText" name="comment" placeholder="Escreva seu comentário..."></textarea><p id="commentError" class="comment-error" role="alert"></p><p class="comment-login-message">Seu nome será exibido junto ao comentário.</p><button id="commentButton" class="comment-button" type="submit">Comentar</button></form></section></section></main>
<?php require __DIR__ . '/../../php/footer.php'; ?><script src="../../assets/JS/script.js"></script></body></html>
